concert1 = Concert.create({name: "Concert 1", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50,  description: "Description"})
concert2 = Concert.create({name: "Concert 2", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Description"}) 
concert3 = Concert.create({name: "Concert 3", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Hidescription"})
concert4 = Concert.create({name: "Concert 4", date: Date.today, artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Description"})
concert5 = Concert.create({name: "Concert 5", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Description"})
concert6 = Concert.create({name: "Concert 6", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Description"}) 
concert7 = Concert.create({name: "Concert 7", date: Date.today,  artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Hidescription"})
concert8 = Concert.create({name: "Concert 8", date: Date.today, artist: "2chainz", venue: "O2 Arena", city: "Miami", ticketprice: 50, description: "Description"})
